# coding: utf-8

# flake8: noqa

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "SearchApi",
    "WebApi",
    "WeblichtApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AdvancedLayer",
    "AdvancedLayers",
    "CancellableOperationObjectObject",
    "ConsortiaList",
    "DataView",
    "Diagnostic",
    "Endpoint",
    "EndpointStatistics",
    "EndpointStats",
    "ExampleQuery",
    "GetStatisticsForTypeDefaultResponse",
    "IndexView",
    "InitData",
    "Institution",
    "JavaException",
    "JsonMetaOnlySearch",
    "JsonSearch",
    "Kwic",
    "LanguageMap",
    "Layer",
    "LexEntry",
    "LexField",
    "ModelField",
    "PiwikConfig",
    "Resource",
    "ResourceInfo",
    "Result",
    "ResultMeta",
    "ResultRecord",
    "ScanSearchStatistics",
    "SearchJobStatistics",
    "Span",
    "TextFragment",
    "Value",
]

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi
from openapi_client.api.search_api import SearchApi as SearchApi
from openapi_client.api.web_api import WebApi as WebApi
from openapi_client.api.weblicht_api import WeblichtApi as WeblichtApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.advanced_layer import AdvancedLayer as AdvancedLayer
from openapi_client.models.advanced_layers import AdvancedLayers as AdvancedLayers
from openapi_client.models.cancellable_operation_object_object import CancellableOperationObjectObject as CancellableOperationObjectObject
from openapi_client.models.consortia_list import ConsortiaList as ConsortiaList
from openapi_client.models.data_view import DataView as DataView
from openapi_client.models.diagnostic import Diagnostic as Diagnostic
from openapi_client.models.endpoint import Endpoint as Endpoint
from openapi_client.models.endpoint_statistics import EndpointStatistics as EndpointStatistics
from openapi_client.models.endpoint_stats import EndpointStats as EndpointStats
from openapi_client.models.example_query import ExampleQuery as ExampleQuery
from openapi_client.models.get_statistics_for_type_default_response import GetStatisticsForTypeDefaultResponse as GetStatisticsForTypeDefaultResponse
from openapi_client.models.index_view import IndexView as IndexView
from openapi_client.models.init_data import InitData as InitData
from openapi_client.models.institution import Institution as Institution
from openapi_client.models.java_exception import JavaException as JavaException
from openapi_client.models.json_meta_only_search import JsonMetaOnlySearch as JsonMetaOnlySearch
from openapi_client.models.json_search import JsonSearch as JsonSearch
from openapi_client.models.kwic import Kwic as Kwic
from openapi_client.models.language_map import LanguageMap as LanguageMap
from openapi_client.models.layer import Layer as Layer
from openapi_client.models.lex_entry import LexEntry as LexEntry
from openapi_client.models.lex_field import LexField as LexField
from openapi_client.models.model_field import ModelField as ModelField
from openapi_client.models.piwik_config import PiwikConfig as PiwikConfig
from openapi_client.models.resource import Resource as Resource
from openapi_client.models.resource_info import ResourceInfo as ResourceInfo
from openapi_client.models.result import Result as Result
from openapi_client.models.result_meta import ResultMeta as ResultMeta
from openapi_client.models.result_record import ResultRecord as ResultRecord
from openapi_client.models.scan_search_statistics import ScanSearchStatistics as ScanSearchStatistics
from openapi_client.models.search_job_statistics import SearchJobStatistics as SearchJobStatistics
from openapi_client.models.span import Span as Span
from openapi_client.models.text_fragment import TextFragment as TextFragment
from openapi_client.models.value import Value as Value

