import re
from pathlib import Path

from setuptools import setup

here = Path(__file__).resolve().parent
init_py = here / "__init__.py"
version = "1.0.0"
if init_py.exists():
    content = init_py.read_text(encoding="utf-8")
    match = re.search(r'^__version__ = ["\']([^"\']+)["\']', content, re.M)
    if match:
        version = match.group(1)

setup(
    name="textplus-openapi-python",
    version=version,
    author="OpenAPI Generator",
    author_email="info@example.com",
    description="CLARIN FCS Aggregator REST API Python client generated by OpenAPI Generator.",
    long_description=(here / "README.md").read_text(encoding="utf-8") if (here / "README.md").exists() else "",
    long_description_content_type="text/markdown",
    url="https://github.com/clarin-eric/fcs-sru-aggregator",
    project_urls={
        "Source": "https://github.com/clarin-eric/fcs-sru-aggregator",
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
        "Typing :: Typed",
    ],
    python_requires=">=3.8",
    package_dir={"openapi_client": "."},
    packages=[
        "openapi_client",
        "openapi_client.api",
        "openapi_client.models",
    ],
    install_requires=[
        "python-dateutil>=2.8.0",
        "pydantic>=2.0.0",
        "pydantic-core>=2.0.0",
        "typing-extensions>=4.0.0",
        "urllib3>=1.26.0",
    ],
    include_package_data=True,
    package_data={"openapi_client": ["py.typed"]},
    zip_safe=False,
    keywords="openapi client clarin fcs aggregator",
)
