# coding: utf-8

# flake8: noqa
"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.advanced_layer import AdvancedLayer
from openapi_client.models.advanced_layers import AdvancedLayers
from openapi_client.models.cancellable_operation_object_object import CancellableOperationObjectObject
from openapi_client.models.consortia_list import ConsortiaList
from openapi_client.models.data_view import DataView
from openapi_client.models.diagnostic import Diagnostic
from openapi_client.models.endpoint import Endpoint
from openapi_client.models.endpoint_statistics import EndpointStatistics
from openapi_client.models.endpoint_stats import EndpointStats
from openapi_client.models.example_query import ExampleQuery
from openapi_client.models.get_statistics_for_type_default_response import GetStatisticsForTypeDefaultResponse
from openapi_client.models.index_view import IndexView
from openapi_client.models.init_data import InitData
from openapi_client.models.institution import Institution
from openapi_client.models.java_exception import JavaException
from openapi_client.models.json_meta_only_search import JsonMetaOnlySearch
from openapi_client.models.json_search import JsonSearch
from openapi_client.models.kwic import Kwic
from openapi_client.models.language_map import LanguageMap
from openapi_client.models.layer import Layer
from openapi_client.models.lex_entry import LexEntry
from openapi_client.models.lex_field import LexField
from openapi_client.models.model_field import ModelField
from openapi_client.models.piwik_config import PiwikConfig
from openapi_client.models.resource import Resource
from openapi_client.models.resource_info import ResourceInfo
from openapi_client.models.result import Result
from openapi_client.models.result_meta import ResultMeta
from openapi_client.models.result_record import ResultRecord
from openapi_client.models.scan_search_statistics import ScanSearchStatistics
from openapi_client.models.search_job_statistics import SearchJobStatistics
from openapi_client.models.span import Span
from openapi_client.models.text_fragment import TextFragment
from openapi_client.models.value import Value

