# coding: utf-8

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from openapi_client.models.endpoint_stats import EndpointStats
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EndpointStatistics(BaseModel):
    """
    EndpointStatistics
    """ # noqa: E501
    timeout: Union[StrictFloat, StrictInt]
    is_scan: StrictBool = Field(alias="isScan")
    institutions: Dict[str, Dict[str, EndpointStats]]
    var_date: datetime = Field(alias="date")
    __properties: ClassVar[List[str]] = ["timeout", "isScan", "institutions", "date"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EndpointStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in institutions (dict of dict)
        _field_dict_of_dict = {}
        if self.institutions:
            for _key_institutions, _value_institutions in self.institutions.items():
                if _value_institutions is not None:
                    _field_dict_of_dict[_key_institutions] = {
                        _key: _value.to_dict() for _key, _value in _value_institutions.items()
                    }
            _dict['institutions'] = _field_dict_of_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EndpointStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timeout": obj.get("timeout"),
            "isScan": obj.get("isScan"),
            "institutions": dict(
                (_k, dict(
                    (_ik, EndpointStats.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj["institutions"].items()
            )
            if obj.get("institutions") is not None
            else None,
            "date": obj.get("date")
        })
        return _obj


