# coding: utf-8

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.resource_info import ResourceInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EndpointStats(BaseModel):
    """
    EndpointStats
    """ # noqa: E501
    root_resources: Optional[List[ResourceInfo]] = Field(default=None, alias="rootResources")
    number_of_requests_active: Optional[StrictInt] = Field(default=None, alias="numberOfRequestsActive")
    max_concurrent_requests: Optional[StrictInt] = Field(default=None, alias="maxConcurrentRequests")
    avg_queue_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="avgQueueTime")
    max_queue_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxQueueTime")
    avg_execution_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="avgExecutionTime")
    max_execution_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="maxExecutionTime")
    number_of_requests: Optional[StrictInt] = Field(default=None, alias="numberOfRequests")
    __properties: ClassVar[List[str]] = ["rootResources", "numberOfRequestsActive", "maxConcurrentRequests", "avgQueueTime", "maxQueueTime", "avgExecutionTime", "maxExecutionTime", "numberOfRequests"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EndpointStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in root_resources (list)
        _items = []
        if self.root_resources:
            for _item_root_resources in self.root_resources:
                if _item_root_resources:
                    _items.append(_item_root_resources.to_dict())
            _dict['rootResources'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EndpointStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rootResources": [ResourceInfo.from_dict(_item) for _item in obj["rootResources"]] if obj.get("rootResources") is not None else None,
            "numberOfRequestsActive": obj.get("numberOfRequestsActive"),
            "maxConcurrentRequests": obj.get("maxConcurrentRequests"),
            "avgQueueTime": obj.get("avgQueueTime"),
            "maxQueueTime": obj.get("maxQueueTime"),
            "avgExecutionTime": obj.get("avgExecutionTime"),
            "maxExecutionTime": obj.get("maxExecutionTime"),
            "numberOfRequests": obj.get("numberOfRequests")
        })
        return _obj


