# coding: utf-8

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Layer(BaseModel):
    """
    Layer
    """ # noqa: E501
    identifier: Optional[StrictStr] = None
    result_id: Optional[StrictStr] = Field(default=None, alias="resultId")
    layer_type: Optional[StrictStr] = Field(default=None, alias="layerType")
    encoding: Optional[StrictStr] = None
    qualifier: Optional[StrictStr] = None
    alt_value_info: Optional[StrictStr] = Field(default=None, alias="altValueInfo")
    alt_value_info_uri: Optional[StrictStr] = Field(default=None, alias="altValueInfoURI")
    __properties: ClassVar[List[str]] = ["identifier", "resultId", "layerType", "encoding", "qualifier", "altValueInfo", "altValueInfoURI"]

    @field_validator('encoding')
    def encoding_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['VALUE', 'EMPTY']):
            raise ValueError("must be one of enum values ('VALUE', 'EMPTY')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Layer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Layer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "resultId": obj.get("resultId"),
            "layerType": obj.get("layerType"),
            "encoding": obj.get("encoding"),
            "qualifier": obj.get("qualifier"),
            "altValueInfo": obj.get("altValueInfo"),
            "altValueInfoURI": obj.get("altValueInfoURI")
        })
        return _obj


