# coding: utf-8

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.data_view import DataView
from openapi_client.models.endpoint import Endpoint
from openapi_client.models.example_query import ExampleQuery
from openapi_client.models.institution import Institution
from openapi_client.models.layer import Layer
from openapi_client.models.lex_field import LexField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Resource(BaseModel):
    """
    Resource
    """ # noqa: E501
    endpoint_institution: Optional[Institution] = Field(default=None, alias="endpointInstitution")
    endpoint: Optional[Endpoint] = None
    handle: Optional[StrictStr] = None
    number_of_records: Optional[StrictInt] = Field(default=None, alias="numberOfRecords")
    languages: Optional[List[StrictStr]] = None
    landing_page: Optional[StrictStr] = Field(default=None, alias="landingPage")
    title: Optional[Dict[str, StrictStr]] = None
    description: Optional[Dict[str, StrictStr]] = None
    institution: Optional[Dict[str, StrictStr]] = None
    search_capabilities: Optional[List[StrictStr]] = Field(default=None, alias="searchCapabilities")
    availability_restriction: Optional[StrictStr] = Field(default=None, alias="availabilityRestriction")
    available_data_views: Optional[List[DataView]] = Field(default=None, alias="availableDataViews")
    available_layers: Optional[List[Layer]] = Field(default=None, alias="availableLayers")
    available_lex_fields: Optional[List[LexField]] = Field(default=None, alias="availableLexFields")
    example_queries: Optional[List[ExampleQuery]] = Field(default=None, alias="exampleQueries")
    sub_resources: Optional[List[Resource]] = Field(default=None, alias="subResources")
    id: Optional[StrictStr] = None
    search_capabilities_resolved: Optional[List[StrictStr]] = Field(default=None, alias="searchCapabilitiesResolved")
    __properties: ClassVar[List[str]] = ["endpointInstitution", "endpoint", "handle", "numberOfRecords", "languages", "landingPage", "title", "description", "institution", "searchCapabilities", "availabilityRestriction", "availableDataViews", "availableLayers", "availableLexFields", "exampleQueries", "subResources", "id", "searchCapabilitiesResolved"]

    @field_validator('search_capabilities')
    def search_capabilities_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['BASIC_SEARCH', 'ADVANCED_SEARCH', 'LEX_SEARCH', 'AUTHENTICATED_SEARCH']):
                raise ValueError("each list item must be one of ('BASIC_SEARCH', 'ADVANCED_SEARCH', 'LEX_SEARCH', 'AUTHENTICATED_SEARCH')")
        return value

    @field_validator('availability_restriction')
    def availability_restriction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'AUTH_ONLY', 'PERSONAL_IDENTIFIER']):
            raise ValueError("must be one of enum values ('NONE', 'AUTH_ONLY', 'PERSONAL_IDENTIFIER')")
        return value

    @field_validator('search_capabilities_resolved')
    def search_capabilities_resolved_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['BASIC_SEARCH', 'ADVANCED_SEARCH', 'LEX_SEARCH', 'AUTHENTICATED_SEARCH']):
                raise ValueError("each list item must be one of ('BASIC_SEARCH', 'ADVANCED_SEARCH', 'LEX_SEARCH', 'AUTHENTICATED_SEARCH')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Resource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of endpoint_institution
        if self.endpoint_institution:
            _dict['endpointInstitution'] = self.endpoint_institution.to_dict()
        # override the default output from pydantic by calling `to_dict()` of endpoint
        if self.endpoint:
            _dict['endpoint'] = self.endpoint.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in available_data_views (list)
        _items = []
        if self.available_data_views:
            for _item_available_data_views in self.available_data_views:
                if _item_available_data_views:
                    _items.append(_item_available_data_views.to_dict())
            _dict['availableDataViews'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_layers (list)
        _items = []
        if self.available_layers:
            for _item_available_layers in self.available_layers:
                if _item_available_layers:
                    _items.append(_item_available_layers.to_dict())
            _dict['availableLayers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_lex_fields (list)
        _items = []
        if self.available_lex_fields:
            for _item_available_lex_fields in self.available_lex_fields:
                if _item_available_lex_fields:
                    _items.append(_item_available_lex_fields.to_dict())
            _dict['availableLexFields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in example_queries (list)
        _items = []
        if self.example_queries:
            for _item_example_queries in self.example_queries:
                if _item_example_queries:
                    _items.append(_item_example_queries.to_dict())
            _dict['exampleQueries'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_resources (list)
        _items = []
        if self.sub_resources:
            for _item_sub_resources in self.sub_resources:
                if _item_sub_resources:
                    _items.append(_item_sub_resources.to_dict())
            _dict['subResources'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Resource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "endpointInstitution": Institution.from_dict(obj["endpointInstitution"]) if obj.get("endpointInstitution") is not None else None,
            "endpoint": Endpoint.from_dict(obj["endpoint"]) if obj.get("endpoint") is not None else None,
            "handle": obj.get("handle"),
            "numberOfRecords": obj.get("numberOfRecords"),
            "languages": obj.get("languages"),
            "landingPage": obj.get("landingPage"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "institution": obj.get("institution"),
            "searchCapabilities": obj.get("searchCapabilities"),
            "availabilityRestriction": obj.get("availabilityRestriction"),
            "availableDataViews": [DataView.from_dict(_item) for _item in obj["availableDataViews"]] if obj.get("availableDataViews") is not None else None,
            "availableLayers": [Layer.from_dict(_item) for _item in obj["availableLayers"]] if obj.get("availableLayers") is not None else None,
            "availableLexFields": [LexField.from_dict(_item) for _item in obj["availableLexFields"]] if obj.get("availableLexFields") is not None else None,
            "exampleQueries": [ExampleQuery.from_dict(_item) for _item in obj["exampleQueries"]] if obj.get("exampleQueries") is not None else None,
            "subResources": [Resource.from_dict(_item) for _item in obj["subResources"]] if obj.get("subResources") is not None else None,
            "id": obj.get("id"),
            "searchCapabilitiesResolved": obj.get("searchCapabilitiesResolved")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
Resource.model_rebuild(raise_errors=False)

