# coding: utf-8

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from openapi_client.models.endpoint_statistics import EndpointStatistics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScanSearchStatistics(BaseModel):
    """
    ScanSearchStatistics
    """ # noqa: E501
    last_scan: EndpointStatistics = Field(alias="Last Scan")
    recent_searches: EndpointStatistics = Field(alias="Recent Searches")
    __properties: ClassVar[List[str]] = ["Last Scan", "Recent Searches"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScanSearchStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_scan
        if self.last_scan:
            _dict['Last Scan'] = self.last_scan.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recent_searches
        if self.recent_searches:
            _dict['Recent Searches'] = self.recent_searches.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScanSearchStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Last Scan": EndpointStatistics.from_dict(obj["Last Scan"]) if obj.get("Last Scan") is not None else None,
            "Recent Searches": EndpointStatistics.from_dict(obj["Recent Searches"]) if obj.get("Recent Searches") is not None else None
        })
        return _obj


