# coding: utf-8

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchJobStatistics(BaseModel):
    """
    SearchJobStatistics
    """ # noqa: E501
    start_date: StrictInt = Field(alias="startDate")
    num_requests: StrictInt = Field(alias="numRequests")
    num_requests_cancelled: StrictInt = Field(alias="numRequestsCancelled")
    num_requests_in_progress: StrictInt = Field(alias="numRequestsInProgress")
    num_requests_finished: StrictInt = Field(alias="numRequestsFinished")
    expected_time_to_completion: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="expectedTimeToCompletion")
    expected_time_to_completion_per_endpoint: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="expectedTimeToCompletionPerEndpoint")
    num_searches_before: Optional[StrictInt] = Field(default=None, alias="numSearchesBefore")
    num_requests_before: Optional[StrictInt] = Field(default=None, alias="numRequestsBefore")
    expected_time_to_completion_per_endpoint_before: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, alias="expectedTimeToCompletionPerEndpointBefore")
    status: StrictStr
    __properties: ClassVar[List[str]] = ["startDate", "numRequests", "numRequestsCancelled", "numRequestsInProgress", "numRequestsFinished", "expectedTimeToCompletion", "expectedTimeToCompletionPerEndpoint", "numSearchesBefore", "numRequestsBefore", "expectedTimeToCompletionPerEndpointBefore", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchJobStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchJobStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "startDate": obj.get("startDate"),
            "numRequests": obj.get("numRequests"),
            "numRequestsCancelled": obj.get("numRequestsCancelled"),
            "numRequestsInProgress": obj.get("numRequestsInProgress"),
            "numRequestsFinished": obj.get("numRequestsFinished"),
            "expectedTimeToCompletion": obj.get("expectedTimeToCompletion"),
            "expectedTimeToCompletionPerEndpoint": obj.get("expectedTimeToCompletionPerEndpoint"),
            "numSearchesBefore": obj.get("numSearchesBefore"),
            "numRequestsBefore": obj.get("numRequestsBefore"),
            "expectedTimeToCompletionPerEndpointBefore": obj.get("expectedTimeToCompletionPerEndpointBefore"),
            "status": obj.get("status")
        })
        return _obj


