# coding: utf-8

"""
    CLARIN FCS Aggregator REST API

    The CLARIN FCS Aggregator REST API is documented following the open API specification.<br />Code repository is hosted on <a href=\"https://github.com/clarin-eric/fcs-sru-aggregator\">GitHub</a>.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Value(BaseModel):
    """
    Value
    """ # noqa: E501
    value: Optional[StrictStr] = None
    xml_id: Optional[StrictStr] = Field(default=None, alias="xmlId")
    xml_lang: Optional[StrictStr] = Field(default=None, alias="xmlLang")
    lang_uri: Optional[StrictStr] = Field(default=None, alias="langUri")
    preferred: Optional[StrictBool] = None
    ref: Optional[StrictStr] = None
    id_refs: Optional[List[StrictStr]] = Field(default=None, alias="idRefs")
    vocab_ref: Optional[StrictStr] = Field(default=None, alias="vocabRef")
    vocab_value_ref: Optional[StrictStr] = Field(default=None, alias="vocabValueRef")
    type: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    source_ref: Optional[StrictStr] = Field(default=None, alias="sourceRef")
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    __properties: ClassVar[List[str]] = ["value", "xmlId", "xmlLang", "langUri", "preferred", "ref", "idRefs", "vocabRef", "vocabValueRef", "type", "source", "sourceRef", "date"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Value from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Value from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "value": obj.get("value"),
            "xmlId": obj.get("xmlId"),
            "xmlLang": obj.get("xmlLang"),
            "langUri": obj.get("langUri"),
            "preferred": obj.get("preferred"),
            "ref": obj.get("ref"),
            "idRefs": obj.get("idRefs"),
            "vocabRef": obj.get("vocabRef"),
            "vocabValueRef": obj.get("vocabValueRef"),
            "type": obj.get("type"),
            "source": obj.get("source"),
            "sourceRef": obj.get("sourceRef"),
            "date": obj.get("date")
        })
        return _obj


