//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.9037.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class explain {
    
    private serverInfo serverInfoField;
    
    private databaseInfo databaseInfoField;
    
    private indexInfo indexInfoField;
    
    private schemaInfo schemaInfoField;
    
    private configInfo configInfoField;
    
    /// <remarks/>
    public serverInfo serverInfo {
        get {
            return this.serverInfoField;
        }
        set {
            this.serverInfoField = value;
        }
    }
    
    /// <remarks/>
    public databaseInfo databaseInfo {
        get {
            return this.databaseInfoField;
        }
        set {
            this.databaseInfoField = value;
        }
    }
    
    /// <remarks/>
    public indexInfo indexInfo {
        get {
            return this.indexInfoField;
        }
        set {
            this.indexInfoField = value;
        }
    }
    
    /// <remarks/>
    public schemaInfo schemaInfo {
        get {
            return this.schemaInfoField;
        }
        set {
            this.schemaInfoField = value;
        }
    }
    
    /// <remarks/>
    public configInfo configInfo {
        get {
            return this.configInfoField;
        }
        set {
            this.configInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class serverInfo {
    
    private string hostField;
    
    private string portField;
    
    private string databaseField;
    
    private string protocolField;
    
    private string transportField;
    
    private decimal versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string host {
        get {
            return this.hostField;
        }
        set {
            this.hostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string protocol {
        get {
            return this.protocolField;
        }
        set {
            this.protocolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string transport {
        get {
            return this.transportField;
        }
        set {
            this.transportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class databaseInfo {
    
    private title[] titleField;
    
    private description[] descriptionField;
    
    private author[] authorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("title")]
    public title[] title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("description")]
    public description[] description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("author")]
    public author[] author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class title {
    
    private string langField;
    
    private bool primaryField;
    
    private bool primaryFieldSpecified;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool primarySpecified {
        get {
            return this.primaryFieldSpecified;
        }
        set {
            this.primaryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class description {
    
    private string langField;
    
    private bool primaryField;
    
    private bool primaryFieldSpecified;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool primarySpecified {
        get {
            return this.primaryFieldSpecified;
        }
        set {
            this.primaryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class author {
    
    private string langField;
    
    private bool primaryField;
    
    private bool primaryFieldSpecified;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool primarySpecified {
        get {
            return this.primaryFieldSpecified;
        }
        set {
            this.primaryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class indexInfo {
    
    private set setField;
    
    private index indexField;
    
    /// <remarks/>
    public set set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    public index index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class set {
    
    private title[] titleField;
    
    private string identifierField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("title")]
    public title[] title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class index {
    
    private title titleField;
    
    private map mapField;
    
    private bool scanField;
    
    private bool searchField;
    
    private bool sortField;
    
    /// <remarks/>
    public title title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public map map {
        get {
            return this.mapField;
        }
        set {
            this.mapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool scan {
        get {
            return this.scanField;
        }
        set {
            this.scanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool search {
        get {
            return this.searchField;
        }
        set {
            this.searchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sort {
        get {
            return this.sortField;
        }
        set {
            this.sortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class map {
    
    private name nameField;
    
    private bool primaryField;
    
    /// <remarks/>
    public name name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool primary {
        get {
            return this.primaryField;
        }
        set {
            this.primaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class name {
    
    private string setField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="NCName")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class schemaInfo {
    
    private schema schemaField;
    
    /// <remarks/>
    public schema schema {
        get {
            return this.schemaField;
        }
        set {
            this.schemaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class schema {
    
    private title titleField;
    
    private string identifierField;
    
    private string nameField;
    
    /// <remarks/>
    public title title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class configInfo {
    
    private @default defaultField;
    
    private setting settingField;
    
    /// <remarks/>
    public @default @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    public setting setting {
        get {
            return this.settingField;
        }
        set {
            this.settingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class @default {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://explain.z3950.org/dtd/2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://explain.z3950.org/dtd/2.0/", IsNullable=false)]
public partial class setting {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class EndpointDescription {
    
    private string[] capabilitiesField;
    
    private SupportedDataView[] supportedDataViewsField;
    
    private SupportedLexField[] supportedLexFieldsField;
    
    private Resource[] resourcesField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Capability", DataType="anyURI", IsNullable=false)]
    public string[] Capabilities {
        get {
            return this.capabilitiesField;
        }
        set {
            this.capabilitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SupportedDataView", IsNullable=false)]
    public SupportedDataView[] SupportedDataViews {
        get {
            return this.supportedDataViewsField;
        }
        set {
            this.supportedDataViewsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SupportedLexField", IsNullable=false)]
    public SupportedLexField[] SupportedLexFields {
        get {
            return this.supportedLexFieldsField;
        }
        set {
            this.supportedLexFieldsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable=false)]
    public Resource[] Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class SupportedDataView {
    
    private string deliverypolicyField;
    
    private string idField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("delivery-policy", DataType="NCName")]
    public string deliverypolicy {
        get {
            return this.deliverypolicyField;
        }
        set {
            this.deliverypolicyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class SupportedLexField {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="NCName")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class Resource {
    
    private Title[] titleField;
    
    private Description[] descriptionField;
    
    private Institution[] institutionField;
    
    private string landingPageURIField;
    
    private Languages languagesField;
    
    private AvailableDataViews availableDataViewsField;
    
    private AvailableLexFields availableLexFieldsField;
    
    private ExampleQuery[] exampleQueryField;
    
    private string pidFieldValue;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Title")]
    public Title[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public Description[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Institution")]
    public Institution[] Institution {
        get {
            return this.institutionField;
        }
        set {
            this.institutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string LandingPageURI {
        get {
            return this.landingPageURIField;
        }
        set {
            this.landingPageURIField = value;
        }
    }
    
    /// <remarks/>
    public Languages Languages {
        get {
            return this.languagesField;
        }
        set {
            this.languagesField = value;
        }
    }
    
    /// <remarks/>
    public AvailableDataViews AvailableDataViews {
        get {
            return this.availableDataViewsField;
        }
        set {
            this.availableDataViewsField = value;
        }
    }
    
    /// <remarks/>
    public AvailableLexFields AvailableLexFields {
        get {
            return this.availableLexFieldsField;
        }
        set {
            this.availableLexFieldsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExampleQuery")]
    public ExampleQuery[] ExampleQuery {
        get {
            return this.exampleQueryField;
        }
        set {
            this.exampleQueryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string pid {
        get {
            return this.pidFieldValue;
        }
        set {
            this.pidFieldValue = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class Title {
    
    private string langField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class Description {
    
    private string langField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class Institution {
    
    private string langField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class Languages {
    
    private string languageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class AvailableDataViews {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class AvailableLexFields {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class ExampleQuery {
    
    private string queryField;
    
    private Description[] descriptionField;
    
    private string typeField;
    
    /// <remarks/>
    public string Query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public Description[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class Capabilities {
    
    private string[] capabilityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Capability", DataType="anyURI")]
    public string[] Capability {
        get {
            return this.capabilityField;
        }
        set {
            this.capabilityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class SupportedDataViews {
    
    private SupportedDataView[] supportedDataViewField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SupportedDataView")]
    public SupportedDataView[] SupportedDataView {
        get {
            return this.supportedDataViewField;
        }
        set {
            this.supportedDataViewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class SupportedLexFields {
    
    private SupportedLexField[] supportedLexFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SupportedLexField")]
    public SupportedLexField[] SupportedLexField {
        get {
            return this.supportedLexFieldField;
        }
        set {
            this.supportedLexFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/endpoint-description")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/endpoint-description", IsNullable=false)]
public partial class Resources {
    
    private Resource[] resourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Resource")]
    public Resource[] Resource {
        get {
            return this.resourceField;
        }
        set {
            this.resourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class explainResponse : sruResponseversion {
    
    private recordEntry recordField;
    
    private sruResponseversion echoedExplainRequestField;
    
    private extraResponseData extraResponseDataField;
    
    /// <remarks/>
    public recordEntry record {
        get {
            return this.recordField;
        }
        set {
            this.recordField = value;
        }
    }
    
    /// <remarks/>
    public sruResponseversion echoedExplainRequest {
        get {
            return this.echoedExplainRequestField;
        }
        set {
            this.echoedExplainRequestField = value;
        }
    }
    
    /// <remarks/>
    public extraResponseData extraResponseData {
        get {
            return this.extraResponseDataField;
        }
        set {
            this.extraResponseDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class recordEntry {
    
    private string recordSchemaField;
    
    private string recordXMLEscapingField;
    
    private recordData recordDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string recordSchema {
        get {
            return this.recordSchemaField;
        }
        set {
            this.recordSchemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string recordXMLEscaping {
        get {
            return this.recordXMLEscapingField;
        }
        set {
            this.recordXMLEscapingField = value;
        }
    }
    
    /// <remarks/>
    public recordData recordData {
        get {
            return this.recordDataField;
        }
        set {
            this.recordDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class recordData {
    
    private explain explainField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://explain.z3950.org/dtd/2.0/")]
    public explain explain {
        get {
            return this.explainField;
        }
        set {
            this.explainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="sruResponse.version", Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute("echoedExplainRequest", Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class sruResponseversion {
    
    private decimal versionField;
    
    /// <remarks/>
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class extraResponseData {
    
    private EndpointDescription endpointDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://clarin.eu/fcs/endpoint-description")]
    public EndpointDescription EndpointDescription {
        get {
            return this.endpointDescriptionField;
        }
        set {
            this.endpointDescriptionField = value;
        }
    }
}
