//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/Jan/Desktop/CQL/SAMPLE2/MyAntlrTest/FCSParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class FCSParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		L_PAREN=1, R_PAREN=2, L_SQUARE_BRACKET=3, R_SQUARE_BRACKET=4, OR=5, AND=6, 
		NOT=7, FWD_SLASH=8, L_CURLY_BRACKET=9, R_CURLY_BRACKET=10, Q_ONE_OR_MORE=11, 
		Q_ZERO_OR_MORE=12, Q_ZERO_OR_ONE=13, Q_COMMA=14, OPERATOR_EQ=15, OPERATOR_NE=16, 
		COLON=17, WITHIN=18, SIMPLE_WITHIN_SCOPE=19, REGEXP_FLAGS=20, IDENTIFIER=21, 
		INTEGER=22, REGEXP=23, QUOTED_STRING=24, Space=25;
	public const int
		RULE_query = 0, RULE_main_query = 1, RULE_query_disjunction = 2, RULE_query_sequence = 3, 
		RULE_query_group = 4, RULE_query_simple = 5, RULE_quantifier = 6, RULE_query_implicit = 7, 
		RULE_query_segment = 8, RULE_within_part = 9, RULE_within_part_simple = 10, 
		RULE_expression = 11, RULE_expression_or = 12, RULE_expression_and = 13, 
		RULE_expression_group = 14, RULE_expression_not = 15, RULE_expression_basic = 16, 
		RULE_attribute = 17, RULE_qualifier = 18, RULE_identifier = 19, RULE_regexp = 20, 
		RULE_regexp_pattern = 21, RULE_regexp_flag = 22;
	public static readonly string[] ruleNames = {
		"query", "main_query", "query_disjunction", "query_sequence", "query_group", 
		"query_simple", "quantifier", "query_implicit", "query_segment", "within_part", 
		"within_part_simple", "expression", "expression_or", "expression_and", 
		"expression_group", "expression_not", "expression_basic", "attribute", 
		"qualifier", "identifier", "regexp", "regexp_pattern", "regexp_flag"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'['", "']'", "'|'", "'&'", "'!'", "'/'", "'{'", "'}'", 
		"'+'", "'*'", "'?'", "','", "'='", "'!='", "':'", "'within'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "L_PAREN", "R_PAREN", "L_SQUARE_BRACKET", "R_SQUARE_BRACKET", "OR", 
		"AND", "NOT", "FWD_SLASH", "L_CURLY_BRACKET", "R_CURLY_BRACKET", "Q_ONE_OR_MORE", 
		"Q_ZERO_OR_MORE", "Q_ZERO_OR_ONE", "Q_COMMA", "OPERATOR_EQ", "OPERATOR_NE", 
		"COLON", "WITHIN", "SIMPLE_WITHIN_SCOPE", "REGEXP_FLAGS", "IDENTIFIER", 
		"INTEGER", "REGEXP", "QUOTED_STRING", "Space"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FCSParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static FCSParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FCSParser(ITokenStream input) : this(input, TextWriter.Null, TextWriter.Null) { }

		public FCSParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class QueryContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Main_queryContext main_query() {
			return GetRuleContext<Main_queryContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(FCSParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WITHIN() { return GetToken(FCSParser.WITHIN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Within_partContext within_part() {
			return GetRuleContext<Within_partContext>(0);
		}
		public QueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query; } }
	}

	[RuleVersion(0)]
	public QueryContext query() {
		QueryContext _localctx = new QueryContext(Context, State);
		EnterRule(_localctx, 0, RULE_query);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46;
			main_query();
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==WITHIN) {
				{
				State = 47;
				Match(WITHIN);
				State = 48;
				within_part();
				}
			}

			State = 51;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Main_queryContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Query_simpleContext query_simple() {
			return GetRuleContext<Query_simpleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_groupContext query_group() {
			return GetRuleContext<Query_groupContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_sequenceContext query_sequence() {
			return GetRuleContext<Query_sequenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_disjunctionContext query_disjunction() {
			return GetRuleContext<Query_disjunctionContext>(0);
		}
		public Main_queryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_main_query; } }
	}

	[RuleVersion(0)]
	public Main_queryContext main_query() {
		Main_queryContext _localctx = new Main_queryContext(Context, State);
		EnterRule(_localctx, 2, RULE_main_query);
		try {
			State = 57;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 53;
				query_simple();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 54;
				query_group();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 55;
				query_sequence();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 56;
				query_disjunction();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Query_disjunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Query_simpleContext[] query_simple() {
			return GetRuleContexts<Query_simpleContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_simpleContext query_simple(int i) {
			return GetRuleContext<Query_simpleContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_sequenceContext[] query_sequence() {
			return GetRuleContexts<Query_sequenceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_sequenceContext query_sequence(int i) {
			return GetRuleContext<Query_sequenceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_groupContext[] query_group() {
			return GetRuleContexts<Query_groupContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_groupContext query_group(int i) {
			return GetRuleContext<Query_groupContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OR() { return GetTokens(FCSParser.OR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR(int i) {
			return GetToken(FCSParser.OR, i);
		}
		public Query_disjunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query_disjunction; } }
	}

	[RuleVersion(0)]
	public Query_disjunctionContext query_disjunction() {
		Query_disjunctionContext _localctx = new Query_disjunctionContext(Context, State);
		EnterRule(_localctx, 4, RULE_query_disjunction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 59;
				query_simple();
				}
				break;
			case 2:
				{
				State = 60;
				query_sequence();
				}
				break;
			case 3:
				{
				State = 61;
				query_group();
				}
				break;
			}
			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 64;
				Match(OR);
				State = 68;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
				case 1:
					{
					State = 65;
					query_simple();
					}
					break;
				case 2:
					{
					State = 66;
					query_sequence();
					}
					break;
				case 3:
					{
					State = 67;
					query_group();
					}
					break;
				}
				}
				}
				State = 72;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==OR );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Query_sequenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Query_simpleContext[] query_simple() {
			return GetRuleContexts<Query_simpleContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_simpleContext query_simple(int i) {
			return GetRuleContext<Query_simpleContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_groupContext[] query_group() {
			return GetRuleContexts<Query_groupContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_groupContext query_group(int i) {
			return GetRuleContext<Query_groupContext>(i);
		}
		public Query_sequenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query_sequence; } }
	}

	[RuleVersion(0)]
	public Query_sequenceContext query_sequence() {
		Query_sequenceContext _localctx = new Query_sequenceContext(Context, State);
		EnterRule(_localctx, 6, RULE_query_sequence);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 76;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case L_SQUARE_BRACKET:
				case REGEXP:
					{
					State = 74;
					query_simple();
					}
					break;
				case L_PAREN:
					{
					State = 75;
					query_group();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 8388618L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Query_groupContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_PAREN() { return GetToken(FCSParser.L_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_PAREN() { return GetToken(FCSParser.R_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Query_disjunctionContext query_disjunction() {
			return GetRuleContext<Query_disjunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_sequenceContext query_sequence() {
			return GetRuleContext<Query_sequenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QuantifierContext quantifier() {
			return GetRuleContext<QuantifierContext>(0);
		}
		public Query_groupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query_group; } }
	}

	[RuleVersion(0)]
	public Query_groupContext query_group() {
		Query_groupContext _localctx = new Query_groupContext(Context, State);
		EnterRule(_localctx, 8, RULE_query_group);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			Match(L_PAREN);
			State = 83;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				{
				State = 81;
				query_disjunction();
				}
				break;
			case 2:
				{
				State = 82;
				query_sequence();
				}
				break;
			}
			State = 85;
			Match(R_PAREN);
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 14848L) != 0)) {
				{
				State = 86;
				quantifier();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Query_simpleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Query_implicitContext query_implicit() {
			return GetRuleContext<Query_implicitContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Query_segmentContext query_segment() {
			return GetRuleContext<Query_segmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QuantifierContext quantifier() {
			return GetRuleContext<QuantifierContext>(0);
		}
		public Query_simpleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query_simple; } }
	}

	[RuleVersion(0)]
	public Query_simpleContext query_simple() {
		Query_simpleContext _localctx = new Query_simpleContext(Context, State);
		EnterRule(_localctx, 10, RULE_query_simple);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case REGEXP:
				{
				State = 89;
				query_implicit();
				}
				break;
			case L_SQUARE_BRACKET:
				{
				State = 90;
				query_segment();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 94;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 14848L) != 0)) {
				{
				State = 93;
				quantifier();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QuantifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Q_ONE_OR_MORE() { return GetToken(FCSParser.Q_ONE_OR_MORE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Q_ZERO_OR_MORE() { return GetToken(FCSParser.Q_ZERO_OR_MORE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Q_ZERO_OR_ONE() { return GetToken(FCSParser.Q_ZERO_OR_ONE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_CURLY_BRACKET() { return GetToken(FCSParser.L_CURLY_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_CURLY_BRACKET() { return GetToken(FCSParser.R_CURLY_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INTEGER() { return GetTokens(FCSParser.INTEGER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTEGER(int i) {
			return GetToken(FCSParser.INTEGER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Q_COMMA() { return GetToken(FCSParser.Q_COMMA, 0); }
		public QuantifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_quantifier; } }
	}

	[RuleVersion(0)]
	public QuantifierContext quantifier() {
		QuantifierContext _localctx = new QuantifierContext(Context, State);
		EnterRule(_localctx, 12, RULE_quantifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Q_ONE_OR_MORE:
				{
				State = 96;
				Match(Q_ONE_OR_MORE);
				}
				break;
			case Q_ZERO_OR_MORE:
				{
				State = 97;
				Match(Q_ZERO_OR_MORE);
				}
				break;
			case Q_ZERO_OR_ONE:
				{
				State = 98;
				Match(Q_ZERO_OR_ONE);
				}
				break;
			case L_CURLY_BRACKET:
				{
				{
				State = 99;
				Match(L_CURLY_BRACKET);
				State = 111;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
				case 1:
					{
					State = 100;
					Match(INTEGER);
					}
					break;
				case 2:
					{
					State = 102;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==INTEGER) {
						{
						State = 101;
						Match(INTEGER);
						}
					}

					State = 104;
					Match(Q_COMMA);
					State = 105;
					Match(INTEGER);
					}
					break;
				case 3:
					{
					State = 106;
					Match(INTEGER);
					State = 107;
					Match(Q_COMMA);
					State = 109;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==INTEGER) {
						{
						State = 108;
						Match(INTEGER);
						}
					}

					}
					break;
				}
				State = 113;
				Match(R_CURLY_BRACKET);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Query_implicitContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RegexpContext regexp() {
			return GetRuleContext<RegexpContext>(0);
		}
		public Query_implicitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query_implicit; } }
	}

	[RuleVersion(0)]
	public Query_implicitContext query_implicit() {
		Query_implicitContext _localctx = new Query_implicitContext(Context, State);
		EnterRule(_localctx, 14, RULE_query_implicit);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			regexp();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Query_segmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_SQUARE_BRACKET() { return GetToken(FCSParser.L_SQUARE_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_SQUARE_BRACKET() { return GetToken(FCSParser.R_SQUARE_BRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Query_segmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query_segment; } }
	}

	[RuleVersion(0)]
	public Query_segmentContext query_segment() {
		Query_segmentContext _localctx = new Query_segmentContext(Context, State);
		EnterRule(_localctx, 16, RULE_query_segment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			Match(L_SQUARE_BRACKET);
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 3932290L) != 0)) {
				{
				State = 119;
				expression();
				}
			}

			State = 122;
			Match(R_SQUARE_BRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Within_partContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Within_part_simpleContext within_part_simple() {
			return GetRuleContext<Within_part_simpleContext>(0);
		}
		public Within_partContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_within_part; } }
	}

	[RuleVersion(0)]
	public Within_partContext within_part() {
		Within_partContext _localctx = new Within_partContext(Context, State);
		EnterRule(_localctx, 18, RULE_within_part);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			within_part_simple();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Within_part_simpleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SIMPLE_WITHIN_SCOPE() { return GetToken(FCSParser.SIMPLE_WITHIN_SCOPE, 0); }
		public Within_part_simpleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_within_part_simple; } }
	}

	[RuleVersion(0)]
	public Within_part_simpleContext within_part_simple() {
		Within_part_simpleContext _localctx = new Within_part_simpleContext(Context, State);
		EnterRule(_localctx, 20, RULE_within_part_simple);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			Match(SIMPLE_WITHIN_SCOPE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expression_basicContext expression_basic() {
			return GetRuleContext<Expression_basicContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_notContext expression_not() {
			return GetRuleContext<Expression_notContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_groupContext expression_group() {
			return GetRuleContext<Expression_groupContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_orContext expression_or() {
			return GetRuleContext<Expression_orContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_andContext expression_and() {
			return GetRuleContext<Expression_andContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_expression);
		try {
			State = 133;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 128;
				expression_basic();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 129;
				expression_not();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 130;
				expression_group();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 131;
				expression_or();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 132;
				expression_and();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_orContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expression_basicContext[] expression_basic() {
			return GetRuleContexts<Expression_basicContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_basicContext expression_basic(int i) {
			return GetRuleContext<Expression_basicContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_groupContext[] expression_group() {
			return GetRuleContexts<Expression_groupContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_groupContext expression_group(int i) {
			return GetRuleContext<Expression_groupContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_notContext[] expression_not() {
			return GetRuleContexts<Expression_notContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_notContext expression_not(int i) {
			return GetRuleContext<Expression_notContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_andContext[] expression_and() {
			return GetRuleContexts<Expression_andContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_andContext expression_and(int i) {
			return GetRuleContext<Expression_andContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OR() { return GetTokens(FCSParser.OR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR(int i) {
			return GetToken(FCSParser.OR, i);
		}
		public Expression_orContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_or; } }
	}

	[RuleVersion(0)]
	public Expression_orContext expression_or() {
		Expression_orContext _localctx = new Expression_orContext(Context, State);
		EnterRule(_localctx, 24, RULE_expression_or);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				{
				State = 135;
				expression_basic();
				}
				break;
			case 2:
				{
				State = 136;
				expression_group();
				}
				break;
			case 3:
				{
				State = 137;
				expression_not();
				}
				break;
			case 4:
				{
				State = 138;
				expression_and();
				}
				break;
			}
			State = 148;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 141;
					Match(OR);
					State = 146;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
					case 1:
						{
						State = 142;
						expression_basic();
						}
						break;
					case 2:
						{
						State = 143;
						expression_group();
						}
						break;
					case 3:
						{
						State = 144;
						expression_not();
						}
						break;
					case 4:
						{
						State = 145;
						expression_and();
						}
						break;
					}
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 150;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_andContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expression_basicContext[] expression_basic() {
			return GetRuleContexts<Expression_basicContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_basicContext expression_basic(int i) {
			return GetRuleContext<Expression_basicContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_groupContext[] expression_group() {
			return GetRuleContexts<Expression_groupContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_groupContext expression_group(int i) {
			return GetRuleContext<Expression_groupContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_notContext[] expression_not() {
			return GetRuleContexts<Expression_notContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_notContext expression_not(int i) {
			return GetRuleContext<Expression_notContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AND() { return GetTokens(FCSParser.AND); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND(int i) {
			return GetToken(FCSParser.AND, i);
		}
		public Expression_andContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_and; } }
	}

	[RuleVersion(0)]
	public Expression_andContext expression_and() {
		Expression_andContext _localctx = new Expression_andContext(Context, State);
		EnterRule(_localctx, 26, RULE_expression_and);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case WITHIN:
			case SIMPLE_WITHIN_SCOPE:
			case REGEXP_FLAGS:
			case IDENTIFIER:
				{
				State = 152;
				expression_basic();
				}
				break;
			case L_PAREN:
				{
				State = 153;
				expression_group();
				}
				break;
			case NOT:
				{
				State = 154;
				expression_not();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 163;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 157;
					Match(AND);
					State = 161;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case WITHIN:
					case SIMPLE_WITHIN_SCOPE:
					case REGEXP_FLAGS:
					case IDENTIFIER:
						{
						State = 158;
						expression_basic();
						}
						break;
					case L_PAREN:
						{
						State = 159;
						expression_group();
						}
						break;
					case NOT:
						{
						State = 160;
						expression_not();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 165;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_groupContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode L_PAREN() { return GetToken(FCSParser.L_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode R_PAREN() { return GetToken(FCSParser.R_PAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expression_basicContext expression_basic() {
			return GetRuleContext<Expression_basicContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_notContext expression_not() {
			return GetRuleContext<Expression_notContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_orContext expression_or() {
			return GetRuleContext<Expression_orContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_andContext expression_and() {
			return GetRuleContext<Expression_andContext>(0);
		}
		public Expression_groupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_group; } }
	}

	[RuleVersion(0)]
	public Expression_groupContext expression_group() {
		Expression_groupContext _localctx = new Expression_groupContext(Context, State);
		EnterRule(_localctx, 28, RULE_expression_group);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			Match(L_PAREN);
			State = 172;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
			case 1:
				{
				State = 168;
				expression_basic();
				}
				break;
			case 2:
				{
				State = 169;
				expression_not();
				}
				break;
			case 3:
				{
				State = 170;
				expression_or();
				}
				break;
			case 4:
				{
				State = 171;
				expression_and();
				}
				break;
			}
			State = 174;
			Match(R_PAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_notContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(FCSParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expression_basicContext expression_basic() {
			return GetRuleContext<Expression_basicContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_notContext expression_not() {
			return GetRuleContext<Expression_notContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_orContext expression_or() {
			return GetRuleContext<Expression_orContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_andContext expression_and() {
			return GetRuleContext<Expression_andContext>(0);
		}
		public Expression_notContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_not; } }
	}

	[RuleVersion(0)]
	public Expression_notContext expression_not() {
		Expression_notContext _localctx = new Expression_notContext(Context, State);
		EnterRule(_localctx, 30, RULE_expression_not);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			Match(NOT);
			State = 181;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				{
				State = 177;
				expression_basic();
				}
				break;
			case 2:
				{
				State = 178;
				expression_not();
				}
				break;
			case 3:
				{
				State = 179;
				expression_or();
				}
				break;
			case 4:
				{
				State = 180;
				expression_and();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_basicContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext attribute() {
			return GetRuleContext<AttributeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RegexpContext regexp() {
			return GetRuleContext<RegexpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPERATOR_EQ() { return GetToken(FCSParser.OPERATOR_EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPERATOR_NE() { return GetToken(FCSParser.OPERATOR_NE, 0); }
		public Expression_basicContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_basic; } }
	}

	[RuleVersion(0)]
	public Expression_basicContext expression_basic() {
		Expression_basicContext _localctx = new Expression_basicContext(Context, State);
		EnterRule(_localctx, 32, RULE_expression_basic);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183;
			attribute();
			State = 184;
			_la = TokenStream.LA(1);
			if ( !(_la==OPERATOR_EQ || _la==OPERATOR_NE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 185;
			regexp();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QualifierContext qualifier() {
			return GetRuleContext<QualifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FCSParser.COLON, 0); }
		public AttributeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute; } }
	}

	[RuleVersion(0)]
	public AttributeContext attribute() {
		AttributeContext _localctx = new AttributeContext(Context, State);
		EnterRule(_localctx, 34, RULE_attribute);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				{
				State = 187;
				qualifier();
				State = 188;
				Match(COLON);
				}
				break;
			}
			State = 192;
			identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(FCSParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WITHIN() { return GetToken(FCSParser.WITHIN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SIMPLE_WITHIN_SCOPE() { return GetToken(FCSParser.SIMPLE_WITHIN_SCOPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REGEXP_FLAGS() { return GetToken(FCSParser.REGEXP_FLAGS, 0); }
		public QualifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifier; } }
	}

	[RuleVersion(0)]
	public QualifierContext qualifier() {
		QualifierContext _localctx = new QualifierContext(Context, State);
		EnterRule(_localctx, 36, RULE_qualifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 3932160L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(FCSParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WITHIN() { return GetToken(FCSParser.WITHIN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SIMPLE_WITHIN_SCOPE() { return GetToken(FCSParser.SIMPLE_WITHIN_SCOPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REGEXP_FLAGS() { return GetToken(FCSParser.REGEXP_FLAGS, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 38, RULE_identifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 3932160L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RegexpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Regexp_patternContext regexp_pattern() {
			return GetRuleContext<Regexp_patternContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FWD_SLASH() { return GetToken(FCSParser.FWD_SLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Regexp_flagContext regexp_flag() {
			return GetRuleContext<Regexp_flagContext>(0);
		}
		public RegexpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_regexp; } }
	}

	[RuleVersion(0)]
	public RegexpContext regexp() {
		RegexpContext _localctx = new RegexpContext(Context, State);
		EnterRule(_localctx, 40, RULE_regexp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 198;
			regexp_pattern();
			State = 201;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==FWD_SLASH) {
				{
				State = 199;
				Match(FWD_SLASH);
				State = 200;
				regexp_flag();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Regexp_patternContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REGEXP() { return GetToken(FCSParser.REGEXP, 0); }
		public Regexp_patternContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_regexp_pattern; } }
	}

	[RuleVersion(0)]
	public Regexp_patternContext regexp_pattern() {
		Regexp_patternContext _localctx = new Regexp_patternContext(Context, State);
		EnterRule(_localctx, 42, RULE_regexp_pattern);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203;
			Match(REGEXP);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Regexp_flagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REGEXP_FLAGS() { return GetToken(FCSParser.REGEXP_FLAGS, 0); }
		public Regexp_flagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_regexp_flag; } }
	}

	[RuleVersion(0)]
	public Regexp_flagContext regexp_flag() {
		Regexp_flagContext _localctx = new Regexp_flagContext(Context, State);
		EnterRule(_localctx, 44, RULE_regexp_flag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 205;
			Match(REGEXP_FLAGS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,25,208,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,1,0,1,0,1,0,3,0,50,8,0,1,0,1,0,1,1,1,1,1,1,1,1,3,1,58,8,1,1,
		2,1,2,1,2,3,2,63,8,2,1,2,1,2,1,2,1,2,3,2,69,8,2,4,2,71,8,2,11,2,12,2,72,
		1,3,1,3,4,3,77,8,3,11,3,12,3,78,1,4,1,4,1,4,3,4,84,8,4,1,4,1,4,3,4,88,
		8,4,1,5,1,5,3,5,92,8,5,1,5,3,5,95,8,5,1,6,1,6,1,6,1,6,1,6,1,6,3,6,103,
		8,6,1,6,1,6,1,6,1,6,1,6,3,6,110,8,6,3,6,112,8,6,1,6,3,6,115,8,6,1,7,1,
		7,1,8,1,8,3,8,121,8,8,1,8,1,8,1,9,1,9,1,10,1,10,1,11,1,11,1,11,1,11,1,
		11,3,11,134,8,11,1,12,1,12,1,12,1,12,3,12,140,8,12,1,12,1,12,1,12,1,12,
		1,12,3,12,147,8,12,4,12,149,8,12,11,12,12,12,150,1,13,1,13,1,13,3,13,156,
		8,13,1,13,1,13,1,13,1,13,3,13,162,8,13,4,13,164,8,13,11,13,12,13,165,1,
		14,1,14,1,14,1,14,1,14,3,14,173,8,14,1,14,1,14,1,15,1,15,1,15,1,15,1,15,
		3,15,182,8,15,1,16,1,16,1,16,1,16,1,17,1,17,1,17,3,17,191,8,17,1,17,1,
		17,1,18,1,18,1,19,1,19,1,20,1,20,1,20,3,20,202,8,20,1,21,1,21,1,22,1,22,
		1,22,0,0,23,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,
		42,44,0,2,1,0,15,16,1,0,18,21,231,0,46,1,0,0,0,2,57,1,0,0,0,4,62,1,0,0,
		0,6,76,1,0,0,0,8,80,1,0,0,0,10,91,1,0,0,0,12,114,1,0,0,0,14,116,1,0,0,
		0,16,118,1,0,0,0,18,124,1,0,0,0,20,126,1,0,0,0,22,133,1,0,0,0,24,139,1,
		0,0,0,26,155,1,0,0,0,28,167,1,0,0,0,30,176,1,0,0,0,32,183,1,0,0,0,34,190,
		1,0,0,0,36,194,1,0,0,0,38,196,1,0,0,0,40,198,1,0,0,0,42,203,1,0,0,0,44,
		205,1,0,0,0,46,49,3,2,1,0,47,48,5,18,0,0,48,50,3,18,9,0,49,47,1,0,0,0,
		49,50,1,0,0,0,50,51,1,0,0,0,51,52,5,0,0,1,52,1,1,0,0,0,53,58,3,10,5,0,
		54,58,3,8,4,0,55,58,3,6,3,0,56,58,3,4,2,0,57,53,1,0,0,0,57,54,1,0,0,0,
		57,55,1,0,0,0,57,56,1,0,0,0,58,3,1,0,0,0,59,63,3,10,5,0,60,63,3,6,3,0,
		61,63,3,8,4,0,62,59,1,0,0,0,62,60,1,0,0,0,62,61,1,0,0,0,63,70,1,0,0,0,
		64,68,5,5,0,0,65,69,3,10,5,0,66,69,3,6,3,0,67,69,3,8,4,0,68,65,1,0,0,0,
		68,66,1,0,0,0,68,67,1,0,0,0,69,71,1,0,0,0,70,64,1,0,0,0,71,72,1,0,0,0,
		72,70,1,0,0,0,72,73,1,0,0,0,73,5,1,0,0,0,74,77,3,10,5,0,75,77,3,8,4,0,
		76,74,1,0,0,0,76,75,1,0,0,0,77,78,1,0,0,0,78,76,1,0,0,0,78,79,1,0,0,0,
		79,7,1,0,0,0,80,83,5,1,0,0,81,84,3,4,2,0,82,84,3,6,3,0,83,81,1,0,0,0,83,
		82,1,0,0,0,84,85,1,0,0,0,85,87,5,2,0,0,86,88,3,12,6,0,87,86,1,0,0,0,87,
		88,1,0,0,0,88,9,1,0,0,0,89,92,3,14,7,0,90,92,3,16,8,0,91,89,1,0,0,0,91,
		90,1,0,0,0,92,94,1,0,0,0,93,95,3,12,6,0,94,93,1,0,0,0,94,95,1,0,0,0,95,
		11,1,0,0,0,96,115,5,11,0,0,97,115,5,12,0,0,98,115,5,13,0,0,99,111,5,9,
		0,0,100,112,5,22,0,0,101,103,5,22,0,0,102,101,1,0,0,0,102,103,1,0,0,0,
		103,104,1,0,0,0,104,105,5,14,0,0,105,112,5,22,0,0,106,107,5,22,0,0,107,
		109,5,14,0,0,108,110,5,22,0,0,109,108,1,0,0,0,109,110,1,0,0,0,110,112,
		1,0,0,0,111,100,1,0,0,0,111,102,1,0,0,0,111,106,1,0,0,0,112,113,1,0,0,
		0,113,115,5,10,0,0,114,96,1,0,0,0,114,97,1,0,0,0,114,98,1,0,0,0,114,99,
		1,0,0,0,115,13,1,0,0,0,116,117,3,40,20,0,117,15,1,0,0,0,118,120,5,3,0,
		0,119,121,3,22,11,0,120,119,1,0,0,0,120,121,1,0,0,0,121,122,1,0,0,0,122,
		123,5,4,0,0,123,17,1,0,0,0,124,125,3,20,10,0,125,19,1,0,0,0,126,127,5,
		19,0,0,127,21,1,0,0,0,128,134,3,32,16,0,129,134,3,30,15,0,130,134,3,28,
		14,0,131,134,3,24,12,0,132,134,3,26,13,0,133,128,1,0,0,0,133,129,1,0,0,
		0,133,130,1,0,0,0,133,131,1,0,0,0,133,132,1,0,0,0,134,23,1,0,0,0,135,140,
		3,32,16,0,136,140,3,28,14,0,137,140,3,30,15,0,138,140,3,26,13,0,139,135,
		1,0,0,0,139,136,1,0,0,0,139,137,1,0,0,0,139,138,1,0,0,0,140,148,1,0,0,
		0,141,146,5,5,0,0,142,147,3,32,16,0,143,147,3,28,14,0,144,147,3,30,15,
		0,145,147,3,26,13,0,146,142,1,0,0,0,146,143,1,0,0,0,146,144,1,0,0,0,146,
		145,1,0,0,0,147,149,1,0,0,0,148,141,1,0,0,0,149,150,1,0,0,0,150,148,1,
		0,0,0,150,151,1,0,0,0,151,25,1,0,0,0,152,156,3,32,16,0,153,156,3,28,14,
		0,154,156,3,30,15,0,155,152,1,0,0,0,155,153,1,0,0,0,155,154,1,0,0,0,156,
		163,1,0,0,0,157,161,5,6,0,0,158,162,3,32,16,0,159,162,3,28,14,0,160,162,
		3,30,15,0,161,158,1,0,0,0,161,159,1,0,0,0,161,160,1,0,0,0,162,164,1,0,
		0,0,163,157,1,0,0,0,164,165,1,0,0,0,165,163,1,0,0,0,165,166,1,0,0,0,166,
		27,1,0,0,0,167,172,5,1,0,0,168,173,3,32,16,0,169,173,3,30,15,0,170,173,
		3,24,12,0,171,173,3,26,13,0,172,168,1,0,0,0,172,169,1,0,0,0,172,170,1,
		0,0,0,172,171,1,0,0,0,173,174,1,0,0,0,174,175,5,2,0,0,175,29,1,0,0,0,176,
		181,5,7,0,0,177,182,3,32,16,0,178,182,3,30,15,0,179,182,3,24,12,0,180,
		182,3,26,13,0,181,177,1,0,0,0,181,178,1,0,0,0,181,179,1,0,0,0,181,180,
		1,0,0,0,182,31,1,0,0,0,183,184,3,34,17,0,184,185,7,0,0,0,185,186,3,40,
		20,0,186,33,1,0,0,0,187,188,3,36,18,0,188,189,5,17,0,0,189,191,1,0,0,0,
		190,187,1,0,0,0,190,191,1,0,0,0,191,192,1,0,0,0,192,193,3,38,19,0,193,
		35,1,0,0,0,194,195,7,1,0,0,195,37,1,0,0,0,196,197,7,1,0,0,197,39,1,0,0,
		0,198,201,3,42,21,0,199,200,5,8,0,0,200,202,3,44,22,0,201,199,1,0,0,0,
		201,202,1,0,0,0,202,41,1,0,0,0,203,204,5,23,0,0,204,43,1,0,0,0,205,206,
		5,20,0,0,206,45,1,0,0,0,27,49,57,62,68,72,76,78,83,87,91,94,102,109,111,
		114,120,133,139,146,150,155,161,165,172,181,190,201
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
