//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.9037.0.
// 

namespace IDS.TextPlus.FCSEndpoint.Basic;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/resource")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/resource", IsNullable=false)]
public partial class Resource {
    
    private ResourceFragment resourceFragmentField;
    
    private string pidField;
    
    /// <remarks/>
    public ResourceFragment ResourceFragment {
        get {
            return this.resourceFragmentField;
        }
        set {
            this.resourceFragmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string pid {
        get {
            return this.pidField;
        }
        set {
            this.pidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/resource")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/resource", IsNullable=false)]
public partial class ResourceFragment {
    
    private DataView dataViewField;
    
    private string refField;
    
    /// <remarks/>
    public DataView DataView {
        get {
            return this.dataViewField;
        }
        set {
            this.dataViewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/resource")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/resource", IsNullable=false)]
public partial class DataView {
    
    private Result resultField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://clarin.eu/fcs/dataview/hits")]
    public Result Result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/dataview/hits")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/dataview/hits", IsNullable=false)]
public partial class Result {
    
    private string[] hitField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hit", DataType="NCName")]
    public string[] Hit {
        get {
            return this.hitField;
        }
        set {
            this.hitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class searchRetrieveResponse {
    
    private decimal versionField;
    
    private string numberOfRecordsField;
    
    private recordEntry[] recordsField;
    
    private string nextRecordPositionField;
    
    private echoedSearchRetrieveRequest echoedSearchRetrieveRequestField;
    
    private string resultCountPrecisionField;
    
    /// <remarks/>
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string numberOfRecords {
        get {
            return this.numberOfRecordsField;
        }
        set {
            this.numberOfRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("record", IsNullable=false)]
    public recordEntry[] records {
        get {
            return this.recordsField;
        }
        set {
            this.recordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string nextRecordPosition {
        get {
            return this.nextRecordPositionField;
        }
        set {
            this.nextRecordPositionField = value;
        }
    }
    
    /// <remarks/>
    public echoedSearchRetrieveRequest echoedSearchRetrieveRequest {
        get {
            return this.echoedSearchRetrieveRequestField;
        }
        set {
            this.echoedSearchRetrieveRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string resultCountPrecision {
        get {
            return this.resultCountPrecisionField;
        }
        set {
            this.resultCountPrecisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class record {
    
    private string recordSchemaField;
    
    private string recordXMLEscapingField;
    
    private recordData recordDataField;
    
    private string recordPositionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string recordSchema {
        get {
            return this.recordSchemaField;
        }
        set {
            this.recordSchemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string recordXMLEscaping {
        get {
            return this.recordXMLEscapingField;
        }
        set {
            this.recordXMLEscapingField = value;
        }
    }
    
    /// <remarks/>
    public recordData recordData {
        get {
            return this.recordDataField;
        }
        set {
            this.recordDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string recordPosition {
        get {
            return this.recordPositionField;
        }
        set {
            this.recordPositionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class recordData {
    
    private Resource resourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://clarin.eu/fcs/resource")]
    public Resource Resource {
        get {
            return this.resourceField;
        }
        set {
            this.resourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class echoedSearchRetrieveRequest {
    
    private decimal versionField;
    
    private string startRecordField;
    
    private string maximumRecordsField;
    
    /// <remarks/>
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string startRecord {
        get {
            return this.startRecordField;
        }
        set {
            this.startRecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string maximumRecords {
        get {
            return this.maximumRecordsField;
        }
        set {
            this.maximumRecordsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class records {
    
    private recordEntry[] recordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("record")]
    public recordEntry[] record {
        get {
            return this.recordField;
        }
        set {
            this.recordField = value;
        }
    }
}
