//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.9037.0.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/resource")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/resource", IsNullable=false)]
public partial class ResourceFragment {
    
    private DataView[] dataViewField;
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataView")]
    public DataView[] DataView {
        get {
            return this.dataViewField;
        }
        set {
            this.dataViewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/resource")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/resource", IsNullable=false)]
public partial class DataView {
    
    private object itemField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Result", typeof(Result), Namespace="http://clarin.eu/fcs/dataview/hits")]
    [System.Xml.Serialization.XmlElementAttribute("Entry", typeof(Entry), Namespace="http://clarin.eu/fcs/dataview/lex")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/dataview/hits")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/dataview/hits", IsNullable=false)]
public partial class Result {
    
    private Hit[] hitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hit")]
    public Hit[] Hit {
        get {
            return this.hitField;
        }
        set {
            this.hitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/dataview/hits")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/dataview/hits", IsNullable=false)]
public partial class Hit {
    
    private string kindField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/dataview/lex")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/dataview/lex", IsNullable=false)]
public partial class Entry {
    
    private Field[] fieldField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field")]
    public Field[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/dataview/lex")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/dataview/lex", IsNullable=false)]
public partial class Field {
    
    private Value[] valueField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Value")]
    public Value[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://clarin.eu/fcs/dataview/lex")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://clarin.eu/fcs/dataview/lex", IsNullable=false)]
public partial class Value {
    
    private bool preferredField;
    
    private bool preferredFieldSpecified;
    
    private string sourceField;
    
    private string typeField;
    
    private string vocabValueRefField;
    
    private string idField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool preferred {
        get {
            return this.preferredField;
        }
        set {
            this.preferredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool preferredSpecified {
        get {
            return this.preferredFieldSpecified;
        }
        set {
            this.preferredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string vocabValueRef {
        get {
            return this.vocabValueRefField;
        }
        set {
            this.vocabValueRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class searchRetrieveResponse {
    
    private decimal versionField;
    
    private string numberOfRecordsField;
    
    private recordEntry[] recordsField;
    
    private string nextRecordPositionField;
    
    private echoedSearchRetrieveRequest echoedSearchRetrieveRequestField;
    
    private string resultCountPrecisionField;
    
    /// <remarks/>
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string numberOfRecords {
        get {
            return this.numberOfRecordsField;
        }
        set {
            this.numberOfRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("record", IsNullable=false)]
    public recordEntry[] records {
        get {
            return this.recordsField;
        }
        set {
            this.recordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string nextRecordPosition {
        get {
            return this.nextRecordPositionField;
        }
        set {
            this.nextRecordPositionField = value;
        }
    }
    
    /// <remarks/>
    public echoedSearchRetrieveRequest echoedSearchRetrieveRequest {
        get {
            return this.echoedSearchRetrieveRequestField;
        }
        set {
            this.echoedSearchRetrieveRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string resultCountPrecision {
        get {
            return this.resultCountPrecisionField;
        }
        set {
            this.resultCountPrecisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class record {
    
    private string recordSchemaField;
    
    private string recordXMLEscapingField;
    
    private recordData recordDataField;
    
    private string recordPositionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string recordSchema {
        get {
            return this.recordSchemaField;
        }
        set {
            this.recordSchemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string recordXMLEscaping {
        get {
            return this.recordXMLEscapingField;
        }
        set {
            this.recordXMLEscapingField = value;
        }
    }
    
    /// <remarks/>
    public recordData recordData {
        get {
            return this.recordDataField;
        }
        set {
            this.recordDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string recordPosition {
        get {
            return this.recordPositionField;
        }
        set {
            this.recordPositionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class echoedSearchRetrieveRequest {
    
    private decimal versionField;
    
    private string startRecordField;
    
    private string maximumRecordsField;
    
    /// <remarks/>
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string startRecord {
        get {
            return this.startRecordField;
        }
        set {
            this.startRecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string maximumRecords {
        get {
            return this.maximumRecordsField;
        }
        set {
            this.maximumRecordsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class records {
    
    private recordEntry[] recordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("record")]
    public recordEntry[] record {
        get {
            return this.recordField;
        }
        set {
            this.recordField = value;
        }
    }
}
