//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.9037.0.
// 

namespace IDS.TextPlus.FCSEndpoint.Error;


  /// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/diagnostic")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/diagnostic", IsNullable=false)]
public partial class diagnostic {
    
    private string uriField;
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class searchRetrieveResponse {
    
    private decimal versionField;
    
    private string numberOfRecordsField;
    
    private diagnostic[] diagnosticsField;
    
    /// <remarks/>
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string numberOfRecords {
        get {
            return this.numberOfRecordsField;
        }
        set {
            this.numberOfRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("diagnostic", Namespace="http://docs.oasis-open.org/ns/search-ws/diagnostic", IsNullable=false)]
    public diagnostic[] diagnostics {
        get {
            return this.diagnosticsField;
        }
        set {
            this.diagnosticsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/ns/search-ws/sruResponse", IsNullable=false)]
public partial class diagnostics {
    
    private diagnostic[] diagnosticField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("diagnostic", Namespace="http://docs.oasis-open.org/ns/search-ws/diagnostic")]
    public diagnostic[] diagnostic {
        get {
            return this.diagnosticField;
        }
        set {
            this.diagnosticField = value;
        }
    }
}
